# build.tcl — Top-level entry point for the pynq-pr Vivado DFX build flow.
#
# Invoked by the Python CLI via: vivado -mode tcl -source build.tcl -tclargs build_config.tcl
#
# This script creates a Vivado project, adds RTL sources, sources the
# user/shipped base block design, then runs the DFX flow in four stages:
#
# All build parameters (project name, part, sources, RMs, etc.) are read
# from build_config.tcl, which is generated by the Python builder.

set config_file [lindex $argv 0]
source $config_file

#do not use vivado 2022.1, DFX doesn't seem to work properly
set vivado_version [version -short]
if { $vivado_version ne "2022.2" } {
    error "ERROR: Vivado 2022.2 is required. Detected: $vivado_version"
}

set script_dir [file dirname [info script]]
source [file join $script_dir utils.tcl]

create_project -force $project_name $proj_dir -part $part_number
if { $board_part ne "" } {
    set_property BOARD_PART $board_part [current_project]
}

add_files $source_files
if { $verilog_defines ne "" } {
    set_property verilog_define $verilog_defines [current_fileset]
}

if { $reconfiguration_method eq "icap" } {
    set versatile_rtl_dir [file join $script_dir .. versatile rtl]
    set versatile_ip_dir  [file join $script_dir .. versatile ip axi3_ctrl_1.0_0_0]
    add_files -fileset sources_1 [glob [file normalize $versatile_rtl_dir]/*.vhd]
    add_files -fileset sources_1 [glob [file normalize $versatile_rtl_dir]/*.v]
    set_property ip_repo_paths [list [file normalize $versatile_ip_dir]] [current_project]
    update_ip_catalog
}

# if { $reconfiguration_method eq "icap" } {
#     set rtl_dir [file join $script_dir .. rtl]
#     add_files -fileset sources_1 [glob [file normalize $rtl_dir]/icape*.v]
# }
set_property source_mgmt_mode All [current_project]
update_compile_order -fileset sources_1

source [file join $script_dir create_bd.tcl]
open_bd_design [get_files *.bd]
set design_name [get_property NAME [current_bd_design]]

source [file join $script_dir create_rp_bdc.tcl]
source [file join $script_dir enable_dfx.tcl]
source [file join $script_dir create_rm.tcl]

current_bd_design [get_bd_designs $design_name]
assign_bd_address
validate_bd_design
save_bd_design

add_files -fileset constrs_1 $pblocks_xdc

# if { $reconfiguration_method eq "icap" } {
#     set constraints_dir [file join $script_dir .. constraints]
#     add_files -fileset constrs_1 [glob [file normalize $constraints_dir]/versatile.xdc]
# }

source [file join $script_dir run_impl.tcl]

exit
